### ISSUE TITLE
[BUG]: PyYAML-5.4.1 fails to build, update to 6.0.1

### ISSUE THREAD

**Issue by lmf-mx** [cdalvaro/homebrew-tap#70]
### Description of the bug

Upstream: https://github.com/yaml/pyyaml/issues/724
Issue detail and answer identifying solution: https://stackoverflow.com/a/76710304

Works if the source in your formula is replaced with the one in the updated brew version at https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyyaml.rb

### Steps To Reproduce

1. brew install cdalvaro/tap/salt
2. error on building PyYAML: (AttributeError: cython_sources)

**Comment by cdalvaro** [comment]
Thank you for reporting the issue @lmf-mx 

<details>
  <summary>This is the full error</summary>
  <pre>
python3.10
-m
pip
--python=/opt/homebrew/Cellar/salt/3006.1/libexec/bin/python
install
--verbose
--no-deps
--no-binary=:all:
--ignore-installed
--use-feature=no-binary-enable-wheel-cache
/private/tmp/salt--PyYAML-20230731-21360-s2e2hu/PyYAML-5.4.1

Using pip 23.0.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
Processing /private/tmp/salt--PyYAML-20230731-21360-s2e2hu/PyYAML-5.4.1
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
  Collecting setuptools
    Using cached setuptools-68.0.0.tar.gz (2.2 MB)
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Installing backend dependencies: started
    Installing backend dependencies: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting wheel
    Using cached wheel-0.41.0.tar.gz (96 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting Cython
    Downloading Cython-3.0.0.tar.gz (2.7 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 39.1 MB/s eta 0:00:00
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Building wheels for collected packages: wheel, setuptools
    Building wheel for wheel (pyproject.toml): started
    Building wheel for wheel (pyproject.toml): finished with status 'done'
    Created wheel for wheel: filename=wheel-0.41.0-py3-none-any.whl size=64712 sha256=c63832c8f4a86e3b5381a724b7947aad568f6850f8bf5c85ac23051c9e4b3b6f
    Stored in directory: /private/tmp/salt-20230731-21360-urxf9/salt-3006.1/.brew_home/Library/Caches/pip/wheels/0b/7d/00/4cb2cf64a0506e2566e7f5829c9fd7373e5a1b02cafea3811d
    Building wheel for setuptools (pyproject.toml): started
    Building wheel for setuptools (pyproject.toml): finished with status 'done'
    Created wheel for setuptools: filename=setuptools-68.0.0-py3-none-any.whl size=804036 sha256=f4866e820eaa1c38e8b4b5e01052d2764f36063aa61ed76ffd6eea6a9e1030ae
    Stored in directory: /private/tmp/salt-20230731-21360-urxf9/salt-3006.1/.brew_home/Library/Caches/pip/wheels/d8/19/2c/701ab02e90fffe29c30f1e17fc21365276d9a51b9e4e4280bc
  Successfully built wheel setuptools
  Installing collected packages: wheel, setuptools, Cython
    DEPRECATION: Cython is being installed using the legacy 'setup.py install' method, because the '--no-binary' option was enabled for it and this currently disables local wheel building for projects that don't have a 'pyproject.toml' file. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/11451
    Running setup.py install for Cython: started
    Running setup.py install for Cython: finished with status 'done'
  Successfully installed Cython-3.0.0 setuptools-68.0.0 wheel-0.41.0

  [notice] A new release of pip is available: 23.0.1 -> 23.2.1
  [notice] To update, run: python -m pip install --upgrade pip
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  /private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!

          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.

          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
      self.find_sources()
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
      mm.run()
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
      self.add_defaults()
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
      sdist.add_defaults(self)
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
      super().add_defaults()
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "<string>", line 201, in get_source_files
    File "/private/tmp/pip-build-env-q3jzt9ob/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  </pre>
</details>
